### PR TITLE
Updated ncp to 2.0.0 and kew to 0.7.0

### PR DESCRIPTION
**Pull request by palmerj3**
This fixes an issue for me where the install script hangs at "Copying extracted folder"

### CODE REVIEW

**Comment by sveisvei** [comment]
Same experience here with node 4.x, install works fine with node 0.10.x.

**Comment by palmerj3** [comment]
@sveisvei does this patch fix that for you?  Seemed to work for me.

**Comment by sveisvei** [comment]
@palmerj3 updating ncp helps on ubuntu with node 4, but to get phantomjs2 on ubuntu we need updated ncp and the download-url fix.

**Comment by eladchen** [comment]
Any ETA on this ? This is a real issue, I don't want people in my department to troubleshoot this every time they run 'npm install'  

EDIT: 
For anyone else struggling with this, use  [npm-shrinkwrap](https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/) ( until the module dependencies are updated )

**Comment by zeevl** [comment]
Thanks @palmerj3.    @eladchen -- ubuntu builds of phantomjs2 are still shoddy, looking into a more universal fix.

**Pull request merged**
